services:
  db:
    image: postgres:16
    container_name: hospital-db
    environment:
      POSTGRES_DB: hospital_db
      POSTGRES_USER: hospital_user
      POSTGRES_PASSWORD: hospital_password
    ports:
      - "15432:5432"
    volumes:
      - hospital-postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U hospital_user -d hospital_db"]
      interval: 5s
      timeout: 3s
      retries: 10

  app:
    build: .
    container_name: hospital-app
    depends_on:
      db:
        condition: service_healthy
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/hospital_db
      SPRING_DATASOURCE_USERNAME: hospital_user
      SPRING_DATASOURCE_PASSWORD: hospital_password
    ports:
      - "8080:8080"

volumes:
  hospital-postgres-data:
