spring:
  application:
    name: hospital-management
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:15432/hospital_db}
    username: ${SPRING_DATASOURCE_USERNAME:hospital_user}
    password: ${SPRING_DATASOURCE_PASSWORD:hospital_password}
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yml

springdoc:
  swagger-ui:
    path: /swagger-ui.html

server:
  port: ${SERVER_PORT:8080}
