spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      routes:
        - id: main-service
          uri: ${MAIN_SERVICE_URL:http://localhost:8081}
          predicates:
            - Path=/api/patients/**
        - id: report-service
          uri: ${REPORT_SERVICE_URL:http://localhost:8082}
          predicates:
            - Path=/api/reports/**

server:
  port: ${SERVER_PORT:8080}
